### PR TITLE
WIP: Remote port forwarding

### LINKED ISSUE #6: Add support for "reverse" forwarding (server listening on local)
At the moment `onetun` supports forwarding outbound connections (from local client to remote server).

It would be especially useful for developers to also have the reverse, namely inbound connections (from remote clients to local servers).

Based on your description on how it uses `smoltun` it seems to be a matter of implementing the reverse logic for the TCP forwarding.

### PR DESCRIPTION
**Pull request by aramperes**
Fixes #6

### CODE REVIEW

**Comment by sini** [comment]
Could you use any help with finishing this?

**Comment by aramperes** [comment]
> Could you use any help with finishing this?

Hey @sini! Yes I got a bit stuck with refactoring the code to support this, and I have other commitments currently. If you want to start a separate draft or if you have any ideas, I'm super open to it! 👍

**Comment by sini** [comment]
> > Could you use any help with finishing this?
> 
> Hey @sini! Yes I got a bit stuck with refactoring the code to support this, and I have other commitments currently. If you want to start a separate draft or if you have any ideas, I'm super open to it! 👍

Thanks for the prompt response! I'm new to rust but have a need for this and would be happy to hack at it versus starting a new project from scratch. I'll try and pick this PR up. :) If you have any notes/pointers for next steps you would have taken I'm sure that could be super helpful.

**Comment by aramperes** [comment]
Closing for now; I will implement piece by piece in `master`.

**Pull request closed without merging**
